### ISSUE TITLE
error occured during build yasm

### ISSUE THREAD

**Issue by wonchulee** [joybro/jhbuild-gstreamer#12]
When I try to build latest jhbuild-gstreamer, I got the error message during build yasm.
I attached it.

**\* Building yasm **\* [17/26]
make -j 8
/usr/bin/python ./modules/arch/x86/gen_x86_insn.py
/usr/bin/python ./modules/arch/x86/gen_x86_insn.py
/usr/bin/python ./modules/arch/x86/gen_x86_insn.py
gcc -std=gnu99  -I.  \
      -c -o genperf.o `test -f tools/genperf/genperf.c || echo './'`tools/genperf/genperf.c
gcc -std=gnu99  -I.  \
      -c -o gp-perfect.o `test -f tools/genperf/perfect.c || echo './'`tools/genperf/perfect.c
gcc -std=gnu99  -I.  \
      -c -o gp-phash.o `test -f libyasm/phash.c || echo './'`libyasm/phash.c
gcc -std=gnu99  -I.  \
      -c -o gp-xmalloc.o `test -f libyasm/xmalloc.c || echo './'`libyasm/xmalloc.c
gcc -std=gnu99  -I.  \
      -c -o gp-xstrdup.o `test -f libyasm/xstrdup.c || echo './'`libyasm/xstrdup.c
gcc -std=gnu99  -I.  \
      -c -o re2c-main.o `test -f tools/re2c/main.c || echo './'`tools/re2c/main.c
gcc -std=gnu99  -I.  \
      -c -o re2c-code.o `test -f tools/re2c/code.c || echo './'`tools/re2c/code.c
gcc -std=gnu99  -I.  \
      -c -o re2c-dfa.o `test -f tools/re2c/dfa.c || echo './'`tools/re2c/dfa.c
gcc -std=gnu99  -I.  \
      -c -o re2c-parser.o `test -f tools/re2c/parser.c || echo './'`tools/re2c/parser.c
gcc -std=gnu99  -I.  \
      -c -o re2c-actions.o `test -f tools/re2c/actions.c || echo './'`tools/re2c/actions.c
gcc -std=gnu99  -I.  \
      -c -o re2c-scanner.o `test -f tools/re2c/scanner.c || echo './'`tools/re2c/scanner.c
gcc -std=gnu99  -I.  \
      -c -o re2c-mbo_getopt.o `test -f tools/re2c/mbo_getopt.c || echo './'`tools/re2c/mbo_getopt.c
gcc -std=gnu99  -I.  \
      -c -o re2c-substr.o `test -f tools/re2c/substr.c || echo './'`tools/re2c/substr.c
gcc -std=gnu99  -I.  \
      -c -o re2c-translate.o `test -f tools/re2c/translate.c || echo './'`tools/re2c/translate.c
gcc -std=gnu99  -I.  \
      -c -o genmacro.o `test -f tools/genmacro/genmacro.c || echo './'`tools/genmacro/genmacro.c
gcc -std=gnu99 -I.  -c -o genversion.o `test -f modules/preprocs/nasm/genversion.c || echo './'`modules/preprocs/nasm/genversion.c
gcc -std=gnu99 -I.  -c -o genstring.o `test -f genstring.c || echo './'`genstring.c
gcc -std=gnu99 -o genperf  genperf.o gp-perfect.o gp-phash.o gp-xmalloc.o gp-xstrdup.o
gcc -std=gnu99 -o genmacro  genmacro.o
./genmacro nasm-macros.c nasm_standard_mac ./modules/parsers/nasm/nasm-std.mac
./genmacro win64-nasm.c win64_nasm_stdmac ./modules/objfmts/coff/win64-nasm.mac
./genmacro win64-gas.c win64_gas_stdmac ./modules/objfmts/coff/win64-gas.mac
gcc -std=gnu99 -o genstring  genstring.o
gcc -std=gnu99 -o re2c  re2c-main.o re2c-code.o re2c-dfa.o re2c-parser.o re2c-actions.o re2c-scanner.o re2c-mbo_getopt.o re2c-substr.o re2c-translate.o
gcc -std=gnu99 -o genversion  genversion.o
./genstring license_msg license.c ./COPYING
./re2c -b -o gas-token.c ./modules/parsers/gas/gas-token.re
./re2c -b -o nasm-token.c ./modules/parsers/nasm/nasm-token.re
./genversion version.mac
./genmacro nasm-version.c nasm_version_mac version.mac
./genperf x86insn_nasm.gperf x86insn_nasm.c
found distinct (A,B) on attempt 19
built perfect hash table of size 512
./genperf x86insn_gas.gperf x86insn_gas.c
1: no keywords section found
make: **\* [x86insn_gas.c] Error 1
make: **\* Waiting for unfinished jobs....

**Comment by joybro** [comment]
It seems mac specific issue. Would you write a patch for this? I can verify the patch on Ubuntu.

**Comment by wonchulee** [comment]
Yes, It was the problem of local machine, I solved it with install related packages in the machine.
I think It does not require any patch. thanks
