### ISSUE TITLE
how can I build with my local git?

### ISSUE THREAD

**Issue by justinjoy** [joybro/jhbuild-gstreamer#17]
should I modify gstreamer.modules?

**Comment by joybro** [comment]
Yes! like I created gstreamer-1.2.modules for 1.2 build :)

I have gstreamer-lg.modules as well for lg build;

**Comment by justinjoy** [comment]
It's a bit annoying. ;(

**Comment by justinjoy** [comment]
I wrote one suggestion for this troublesome work.

https://github.com/justinjoy/jhbuild-gstreamer/wiki

And also, I am gathering FAQ for this.
