### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by AbdealiLoKo** [joybro/jhbuild-gstreamer#18]
I was trying to find a method of installing gstreamer inside jhbuild and came across your repo.

Could you add some installation instructions ? I can't figure out how to use the repo to install gstreamer.

**Comment by joybro** [comment]
@AbdealiJK I'm not sure what you meant by "installing gstreamer inside jhbuild".

"jg build" command will build and install the latest gstreamer to "build" and "install" subdirectory.
