### ISSUE TITLE
bison install fail on mac

### ISSUE THREAD

**Issue by wonchulee** [joybro/jhbuild-gstreamer#2]
When I try to build on mac, package install step failed.
Error message is like,

**\* 설치중 bison **\* [2/21]
make install DESTDIR=/Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
Making install in po
if test "bison" = "gettext-tools"; then \
      ../build-aux/install-sh -c -d /Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/share/gettext/po; \
      for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
        /Users/wonchul/local/bin/install-check -m 644 ./$file \
                /Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/share/gettext/po/$file; \
      done; \
      for file in Makevars; do \
        rm -f /Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/share/gettext/po/$file; \
      done; \
    else \
      : ; \
    fi
Making install in runtime-po
if test "bison" = "gettext-tools"; then \
      ../build-aux/install-sh -c -d /Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/share/gettext/po; \
      for file in Makefile.in.in remove-potcdate.sin quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot   Makevars.template; do \
        /Users/wonchul/local/bin/install-check -m 644 ./$file \
                /Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/share/gettext/po/$file; \
      done; \
      for file in Makevars; do \
        rm -f /Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/share/gettext/po/$file; \
      done; \
    else \
      : ; \
    fi
Making install in .
  GEN      doc/bison.help
 build-aux/install-sh -c -d '/Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/bin'
  /Users/wonchul/local/bin/install-check src/bison '/Users/wonchul/work/jhbuild-gstreamer/install/_jhbuild/root-bison/Users/wonchul/work/jhbuild-gstreamer/install/bin'
/bin/sh: /Users/wonchul/local/bin/install-check: No such file or directory
make[3]: **\* [install-binPROGRAMS] Error 127
make[2]: **\* [install-am] Error 2
make[1]: **\* [install-recursive] Error 1
make: **\* [install] Error 2

**Comment by joybro** [comment]
It failed to find jhbuild's install-check which is usually installed to '$HOME/.local/bin/'.

Do you have a path for install-check in your $PATH? Make sure that you followed Section 2.1 in the following manual.
https://developer.gnome.org/jhbuild/stable/getting-started.html.en#getting-started-install

There will be still other OSX build problems. Patch for that is welcome!
