### ISSUE TITLE
not rebuild gst-plugins-bad after installing the libxml.

### ISSUE THREAD

**Issue by junsoopark** [joybro/jhbuild-gstreamer#27]
I did know that dashdemux of the gst-plugins-bad is not compiled because libxml's version is lower than required.
So I updated the libxml's version to 2.9.2 (required ver is 2.8),
then ran 'jg build' again.
But I can see just the following message.
How can I rebuild the gst-plugins-bad automatically at this moment?

**\* Checking out gst-plugins-bad **\* [20/27]
git remote set-url origin git://anongit.freedesktop.org/git/gstreamer/gst-plugins-bad
git remote update origin
Fetching origin
git rebase origin/master
Current branch master is up to date.
git submodule init
Submodule 'common' () registered for path 'common'
git submodule update
**\* Skipping gst-plugins-bad (package and dependencies not updated) **\* [20/27]

**Comment by joybro** [comment]
Uninstall and clean the module first, then it will be rebuilt.

```
jg uninstall gst-plugins-bad
jg clean gst-plugins-bad
```
