### ISSUE TITLE
joybro is too busy to merge and review PR

### ISSUE THREAD

**Issue by justinjoy** [joybro/jhbuild-gstreamer#28]
It's very severe problem. Tons of PR drops into crack.
Somebody should help, or let joybro maintain this repository.

**Comment by joybro** [comment]
Haha. Sorry for late review. It is because I'm in Bali now for vacation. I can test and review the PRs next week. :)

**Comment by joybro** [comment]
@beergun Could you compile, test and review the PRs?

**Comment by justinjoy** [comment]
Wow, beergun started working! I can close this issue. :)
