### ISSUE TITLE
gmp build error on osx

### ISSUE THREAD

**Issue by wonchulee** [joybro/jhbuild-gstreamer#5]
environment: osx

/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_`echo sec_sqr | sed 's/_$//'`    -Wno-typedef-redefinition -Wno-error=unused-command-line-argument -c -o sec_sqr.lo sec_sqr.c
tmp-redc_1.s:139:17: error: invalid reassignment of non-absolute variable 'L0m4_tmp'
 .set L0m4_tmp, L0m4-Ltab
                ^
make[2]: **\* [redc_1.lo] Error 1

**Comment by joybro** [comment]
This must be fixed by 38838239a2a7f2bb8dfcd57d6322545d1ce91f6e

Please check it again and close this.

**Comment by wonchulee** [comment]
you are genius, thanks!
